import { createSlice } from "@reduxjs/toolkit";

// Initial state for the user slice
const initialState = {
  username: "", // Initially, the username is empty
};

// Create a slice of the Redux state for managing user-related data
const userSlice = createSlice({
  name: "user", // Slice name
  initialState, // Initial state defined above
  reducers: {
    // Reducer function to update the username in the state
    updateUsername(state, action) {
      state.username = action.payload; // Update the username with the payload received from the action
    },
  },
});

// Extract and export the action creators generated by createSlice
export const { updateUsername } = userSlice.actions;

// Export the reducer function generated by createSlice
const userReducer = userSlice.reducer;
export default userReducer;
